In [5]:
import pandas as pd

In [12]:
dataframe = pd.read_csv("ocorrencia_tratado.csv", sep=";")
dataframe

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,****,03/01/2010,12:00:00,0
1,40349,40349,INCIDENTE,BELÉM,PA,SBBE,03/01/2010,11:05:00,0
2,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,03/01/2010,03:00:00,0
3,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,****,04/01/2010,17:30:00,0
4,40324,40324,INCIDENTE,PELOTAS,RS,SBPK,05/01/2010,19:25:00,0
...,...,...,...,...,...,...,...,...,...
6109,80245,80245,INCIDENTE,RECIFE,PE,SBRF,15/08/2021,15:05:00,0
6110,80247,80247,INCIDENTE,PORTO VELHO,RO,SBPV,16/08/2021,02:30:00,0
6111,80251,80251,INCIDENTE,BELÉM,PA,SBBE,17/08/2021,15:45:00,0
6112,80257,80257,ACIDENTE,DOM AQUINO,MT,****,18/08/2021,16:00:00,0
6113,80259,80259,INCIDENTE,CAMPINAS,SP,SBKP,18/08/2021,12:45:00,0